force-app/main/default/objects/Revenue_Line__c/Revenue_Line__c.object-meta.xml
<CustomObject>
    <label>Revenue Line</label>
    <nameField>
        <label>Revenue Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Line__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Lines</relationshipLabel>
    <relationshipName>Revenue_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Line__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RevenueLineTriggerHandler.cls
public class RevenueLineTriggerHandler {
    public static void handleInsert(Map<Id,Revenue_Line__c> revenueLineNewMap){
        Set<Id> oppIdAffected=new Set<Id>();
        for(Revenue_Line__c revLine:revenueLineNewMap.values()){
            if(revLine.Opportunity__c!=null){
                oppIdAffected.add(revLine.Opportunity__c);
            }
        }
        if(!oppIdAffected.isEmpty()){
                    RevenueLineTriggerHandlerHelper.recalculate(oppIdAffected);
        }
    }
    public static void handleUpdate(List<Revenue_Line__c> revenueLinenewList,Map<Id,Revenue_Line__c> revenueLineOldMap){
        Set<Id> oppIdAffected=new Set<Id>();
        for(Revenue_Line__c revLine:revenueLinenewList){
            Revenue_Line__c oldRevLine=revenueLineOldMap.get(revLine.Id);
            if(oldRevLine.Amount__c!=revLine.Amount__c && revLine.Amount__c!=null ){
                oppIdAffected.add(revLine.Opportunity__c);
            }
            if(oldRevLine.Stage__c!=revLine.Stage__c  ){
                oppIdAffected.add(revLine.Opportunity__c);
            }
             if(oldRevLine.Month__c!=revLine.Month__c  ){
                oppIdAffected.add(revLine.Opportunity__c);
            }
            if(oldRevLine.Opportunity__c!=revLine.Opportunity__c){
                oppIdAffected.add(oldRevLine.Opportunity__c);
                oppIdAffected.add(revLine.Opportunity__c);
            }
        }
 			if(!oppIdAffected.isEmpty()){
                    RevenueLineTriggerHandlerHelper.recalculate(oppIdAffected);
        } 
    }
    public static void handleDelete(Map<Id,Revenue_Line__c> revenueLineOldMap){
        Set<Id> oppIdAffected=new Set<Id>();
        for(Revenue_Line__c revLine:revenueLineOldMap.values()){
            if(revLine.Opportunity__c!=null){
                oppIdAffected.add(revLine.Opportunity__c);
            }
        }
 if(!oppIdAffected.isEmpty()){
                    RevenueLineTriggerHandlerHelper.recalculate(oppIdAffected);
        }    }
}