force-app/main/default/objects/Revenue_Line__c/Revenue_Line__c.object-meta.xml
<CustomObject>
    <label>Revenue Line</label>
    <nameField>
        <label>Revenue Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Revenue_Line__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Revenue_Line__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Revenue Lines</relationshipLabel>
    <relationshipName>Revenue_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Revenue_Line__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Datafactory.cls
@isTest
public class Datafactory {
    public static List<Revenue_Line__c> getRevenueLineWithRelatedOpp(){
        List<Revenue_Line__c> revenueLineList=new List<Revenue_Line__c>();
        List<Opportunity> oppList=new List<Opportunity>();
        
        for(Integer i=0;i<200;i++){
            Opportunity opp=new Opportunity(StageName='Prospecting',closeDate=Date.Today(),Name='opp'+i);
            oppList.add(opp);
        }
        if(!oppList.isEmpty()){
            insert oppList;
        }
         for(Integer i=0;i<200;i++){
            Revenue_Line__c rl=new Revenue_Line__c(Amount__c=100,Stage__c='Active',Month__c=Date.Today(),Opportunity__c=oppList[i].Id);
            revenueLineList.add(rl);
        }
        
        return revenueLineList;
    }
    
    public static List<Account> getAccounts(){
        List<Account> accList=new List<Account>();
        for(Integer i=0;i<250;i++){
            Account acc=new Account(Name='Test Account'+i,Industry='Agriculture');
            accList.add(acc);
        }
        return accList;
        
        
    }
}