force-app/main/default/objects/InvoiceComplete__e/InvoiceComplete__e.object-meta.xml
<CustomObject>
    <label>InvoiceComplete</label>
    <pluralLabel>InvoiceCompletes</pluralLabel>
</CustomObject>

force-app/main/default/objects/InvoiceComplete__e/fields/ContentDocumentId__c.field-meta.xml
<CustomField>
    <fullName>ContentDocumentId__c</fullName>
    <label>ContentDocumentId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/InvoiceComplete__e/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>OpportunityId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoiceQueueable.cls
public class InvoiceQueueable implements Queueable, Database.AllowsCallouts {

    private String opportunityId;
    private String lineItemsJson;

    public InvoiceQueueable(String opportunityId, String lineItemsJson) {
        this.opportunityId = opportunityId;
        this.lineItemsJson = lineItemsJson;
    }

    public void execute(QueueableContext ctx) {
        List<InvoiceDTO.LineItemDTO> dtos = (List<InvoiceDTO.LineItemDTO>)
            JSON.deserialize(lineItemsJson, List<InvoiceDTO.LineItemDTO>.class);

        InvoiceDTO.InvoiceResult result =
            InvoiceService.buildInvoice(opportunityId, dtos);

        InvoiceComplete__e event = new InvoiceComplete__e(
            OpportunityId__c     = opportunityId,
            ContentDocumentId__c = result.contentDocumentId
        );
        EventBus.publish(event);
    }
}